### ISSUE TITLE
deploy on openshift

### ISSUE THREAD

**Issue by hadifarnoud** [Magnetme/prerender-docker#12]
apparently your docker image uses root user so I can't deploy the docker image on openshift.

can we fix it? I don't know how

**Comment by hadifarnoud** [comment]
this worked https://github.com/aramalipoor/prerender-docker

if only it had caching too :)

**Comment by rogierslag** [comment]
I'll take a look on how we can integrate that back!

**Comment by rogierslag** [comment]
It no longer uses root!
