### ISSUE TITLE
Ask - Scale out issue

### ISSUE THREAD

**Issue by andrib** [Magnetme/prerender-docker#16]
I'm using docker swarm to deploy the prerender container, and tried to scale the service with replicate=N, and i found the prerender service unstable.

`error closing Chrome tab Error: not opened`

Do you have any idea how to scale out the prerender service using docker?

**Comment by rogierslag** [comment]
We are not running Docker swarm ourselves. However we are running multiple containers of the same image on the same machines and we do not see any problems with that (no instability)

Do the requests work correctly for you? This might be an edge case in the communication with Chrome so it double closes the tab (it seems that way from the error).

Are you using the images on Docker Hub or are you building those yourself? In the latter case, which exact chrome version is used?

**Comment by andrib** [comment]
> Are you using the images on Docker Hub or are you building those yourself?
I'm building my own images using your Dockerfile.
Chrome version installed = HeadlessChrome/66.0.3359.181

The request work correctly, and the pages rendered correctly before the headless Chrome crashed

**Comment by rogierslag** [comment]
We are running on `Running with Chrome version: Google Chrome 66.0.3359.170 `

Could you try whether the same issue remains with Docker tag `magnetme/prerender-docker:v2.3.0`?

**Comment by andrib** [comment]
> Could you try whether the same issue remains with Docker tag magnetme/prerender-docker:v2.3.0?

I saw the crash log had gone, but i'm not sure it will resolve the issues because v2.3.0 failed to render my site, still checking v2.3.0 to correctly render my site, i will let you know the results.

Please consider to close this issue, we are looking to take SSR ways due to prerender performance.

**Comment by rogierslag** [comment]
I’d recommend SSR indeed. Prerender isnt that fast and has a number of quirks

**Comment by andrib** [comment]
i'd decide to not to scale it using docker swarm service replicate=N, i only need one instance with more resources and use redis cache, so this issue disappeared as well.
