### ISSUE TITLE
Not forwarding headers

### ISSUE THREAD

**Issue by knepe** [Magnetme/prerender-docker#22]
This issue refers to `forwardHeaders.js` in /plugins.
When logging `req.headers` I can see that there are headers sent into `tabCreated`. 
But they are not present in `customHeaders` so they seem to vanish at some point and I have not been able to see where. For example Authorization header should be forwarded for my app, but as `customHeaders` is empty  it is not now.

Ex:
`req.Headers:
{ authorization: 'Bearer xxxx',
  host: 'localhost:3000' 
}`
`customHeaders: {}`

Using Chrome 68.0.3440.106

**Comment by rogierslag** [comment]
Hmm this is not something I can reproduce locally. 

I tried the following to reproduce:

1. Setup [`slow server`](https://github.com/rogierslag/slow-server)
1. Run the latest `master` branch of this repository with `yarn start`
1. Request the following URL with curl `curl 'http://localhost:8080/http://localhost:3000?response_time=5000&log_headers=true' -H 'Authorization: Bearer uuid-here'`
1. In the console of `slow-server` which receives the request of `prerender-docker`, we see the headers are properly logged and not left out

```
Slow server started at port 8080
Logging headers: { host: 'localhost:8080',
  'user-agent': 'curl/7.54.0',
  accept: '*/*',
  authorization: 'Bearer uuid-here' }
{"host":"localhost:8080","datetime":"2018-08-21T13:45:49.451Z","client":"::1","response_delay":5000,"response_status":200,"inflight_requests":1}
```

Could it be that your receiving application is not properly receiving the headers instead?

**Comment by knepe** [comment]
Hmm, okay. The things is that I see the header in the request to prerender using Fiddler, but it's not there when prerender requests my URL. I'm using /render?rendertype=pdf&url=xxx
I modified plugins/forwardHeaders.js to add some logging:

`// Set all blacklisted headers as lowercase
const BLACKLISTED = [
	'user-agent',       // Prerender sets her own user agent, which we dont want to override
	'host',             // This is set to the host of prerender, so its wrong to forward
	'accept',           // Let prerender accept everything and handle it
	'accept-encoding',  // We dont want to forward deflate or gzip since prerender will break on those
	'connection',       // No sudden keepalive stuff
	'accept-charset',   // Prerender handles this
	'content-length'    // Since we are rewriting lots of the request, we let prerender recalculate this
];

module.exports = {
	// Since prerender does not forward headers, this causes problems for some crawlers looking for
	// e.g. localized content. This plugin ensures the headers sent to prerender are also set in
	// the Chrome instance. Some headers may be blacklisted and will not be forwarded.
	tabCreated(req, _res, next) {
		console.log("Request headers: ", req.headers);
		const customHeaders = Object.entries(req.headers).map(header => {
			const headerKey = header[0];
			const newHeader = {};
			// If blocked, set a empty value
			newHeader[headerKey] = BLACKLISTED.includes(headerKey) ? '' : header[1];
			console.log("adding header", newHeader);
			return newHeader;
		})
			.filter(header => header[1] == '')
			.reduce((a, b) => Object.assign(a, b), {});

		console.log("Forwarding headers: ", customHeaders);

		const headersObject = {
			headers : {
				...customHeaders,
				'X-Prerender' : '1'
			}
		};
		req.prerender.tab.Network.setExtraHTTPHeaders(headersObject);
		next();
	}
};`

This is the output in the console when running master branch on latest with `yarn start`:
getting http://localhost:50794/xxxx
**Request headers:  { authorization: 'bearer generatedtoken-AfricaWorld',
  host: 'localhost:3000' }**
**adding header { authorization: 'bearer generatedtoken-AfricaWorld' }
adding header { host: '' }
Forwarding headers:  {}**

**Comment by knepe** [comment]
I think I figured out what is wrong. It's the .filter method above that is not working. I edited it to look like this:

`// Set all blacklisted headers as lowercase
const BLACKLISTED = [
	'user-agent',       // Prerender sets her own user agent, which we dont want to override
	'host',             // This is set to the host of prerender, so its wrong to forward
	'accept',           // Let prerender accept everything and handle it
	'accept-encoding',  // We dont want to forward deflate or gzip since prerender will break on those
	'connection',       // No sudden keepalive stuff
	'accept-charset',   // Prerender handles this
	'content-length'    // Since we are rewriting lots of the request, we let prerender recalculate this
];

module.exports = {
	// Since prerender does not forward headers, this causes problems for some crawlers looking for
	// e.g. localized content. This plugin ensures the headers sent to prerender are also set in
	// the Chrome instance. Some headers may be blacklisted and will not be forwarded.
	tabCreated(req, _res, next) {
		const customHeaders = Object.entries(req.headers).map(header => {
			const headerKey = header[0];
			const newHeader = {};
			// If blocked, set a empty value
			newHeader[headerKey] = BLACKLISTED.includes(headerKey) ? '' : header[1];
			return newHeader;
		})
			.filter(header => {
				var hasValue = false;
				for(var prop in header){
					hasValue = (!!header[prop]);
				}
				return hasValue;
			})
			.reduce((a, b) => Object.assign(a, b), {});

		const headersObject = {
			headers : {
				...customHeaders,
				'X-Prerender' : '1'
			}
		};
		req.prerender.tab.Network.setExtraHTTPHeaders(headersObject);
		next();
	}
};
`

and it works correctly

**Comment by rogierslag** [comment]
I figured out what the problem is, will fix it today!

**Comment by knepe** [comment]
Nice! Thank you
